annotations:
  data_folder_path: /data/Boudreault/mandible_videos
  traj_name: traj_slice_y90_sec0
  log_name: trajslicey90sec0.txt
images:
  img_root: /data/Boudreault/mandible_data
merge_trajectories:
  traj_to_merge:
    - traj_slice_y10_sec0.csv
    - traj_slice_y10_sec1.csv
    - traj_slice_y10_sec2.csv
    - traj_slice_y20_sec0.csv
    - traj_slice_y20_sec1.csv
    - traj_slice_y20_sec2.csv
    - traj_slice_y30_sec0.csv
    - traj_slice_y30_sec1.csv
    - traj_slice_y30_sec2.csv
    - traj_slice_y40_sec0.csv
    - traj_slice_y40_sec1.csv
    - traj_slice_y40_sec2.csv
    - traj_slice_y50_sec0.csv
    - traj_slice_y50_sec1.csv
    - traj_slice_y50_sec2.csv
    - traj_slice_y60_sec0.csv
    - traj_slice_y60_sec1.csv
    - traj_slice_y60_sec2.csv
    - traj_slice_y70_sec0.csv
    - traj_slice_y70_sec1.csv
    - traj_slice_y70_sec2.csv
    - traj_slice_y80_sec0.csv
    - traj_slice_y80_sec1.csv
    - traj_slice_y80_sec2.csv
    - traj_slice_y90_sec0.csv
    - traj_slice_y90_sec1.csv
    - traj_slice_y90_sec2.csv
  merged_file_name: traj_slice_y
  train_ratio: 0.75