data:
  dataset_root: C:\Users\anaja\OneDrive\Documents\Ecole\TUHH\Semester 3\Projektarbeit\Dataset_sample
  trajectories_train:
    - traj_random0_mini.csv
    # - traj_random0.csv
  trajectories_valid:
    - traj_random1_mini.csv
    # - traj_random1.csv
  trajectories_test:
    - traj_random2_mini.csv
    # - traj_random2.csv
  rescale_pos: True
training:
  sub_model: 'resnet18' # 'resnet18' 'efficientnet-b0'
  weights_file_addon: ""  # Weights saved in f"{subnet_name}_{cam_str}cams_{nb_hidden}_{weights_file_addon}"
  use_pretrained: True
  cam_inputs:
    - Left
    # - Right
    - Side
  num_fc_hidden_units: 256
  train_bs: 2
  valid_bs: 1
  test_bs: 2
  max_epochs: 5
  patience: 2
  lr: 0.005
  lr_scheduler:
    step_size: 3
    gamma: 0.1
wandb:
  wandb_log: True
  project_name: 'Test-project' # 'Test-project'  'Mandible-tracking'