data:
  dataset_root: C:\Users\anaja\OneDrive\Documents\Ecole\TUHH\Semester 3\Projektarbeit\Dataset_sample
  trajectories_train:
    # - traj_split2D_s25.csv
    - traj_contour0.csv
    # - traj_contour1.csv
    # - traj_split3D1n_s25.csv
    # - traj_split3D1p_s25.csv
  trajectories_valid:
    - traj_contour1.csv
    # - traj_split3D1r_s35.csv
  trajectories_test:
    # - traj_splitYXZ_s20.csv
    # - traj_split_p1Dv2_s25.csv
    - traj_random0.csv
  rescale_pos: True
training:
  sub_model: 'resnet18' # 'resnet18' 'efficientnet-b0'
  weights_file_addon: ""  # Weights saved in f"{subnet_name}_{cam_str}cams_{nb_hidden}_{weights_file_addon}"
  use_pretrained: True
  cam_inputs:
    - Left
    # - Right
    - Side
  num_fc_hidden_units: 256
  train_bs: 2
  valid_bs: 2
  test_bs: 2
  max_epochs: 5
  patience: 2
  lr: 0.005
  lr_scheduler:
    step_size: 3
    gamma: 0.1
wandb:
  wandb_log: False
  project_name: 'Mandible-tracking' # 'Test-project'  'Mandible-tracking'