data:
  dataset_root: /data/Boudreault/mandible_data
  trajectories_train:
    - traj_contour0.csv
    - traj_contour1.csv
    - traj_random_qlbb.csv
    - traj_random_qlbt.csv
    - traj_random_qlfb.csv
    - traj_random_qlft.csv
    - traj_random_qrbb.csv
    - traj_random_qrfb.csv
    - traj_random_qrft.csv
    - traj_random_slf.csv
    - traj_random_srf.csv
    - traj_random_slba.csv
    - traj_random_srba.csv
    - traj_random0.csv
    - traj_random1.csv
  trajectories_valid:
    - traj_random_sft.csv
    - traj_random_sfb.csv
    - traj_random_sbt.csv
    - traj_random_sbb.csv
    - traj_random3.csv
  trajectories_test:
    - traj_random_slbo.csv
    - traj_random_slt.csv
    - traj_random_srbo.csv
    - traj_random_srt.csv
    - traj_random4.csv
    - traj_splitYXZ_s20.csv
  rescale_pos: True
training:
  sub_model: 'resnet18' # 'resnet18' 'efficientnet-b0'
  weights_file_addon: "best_resnet18"  # Weights saved in f"{subnet_name}_{cam_str}cams_{nb_hidden}_{weights_file_addon}"
  use_pretrained: False
  cam_inputs:
    - Left
    - Right
    - Side
  num_fc_hidden_units: 256
  train_bs: 4
  valid_bs: 4
  test_bs: 2
  max_epochs: 30
  patience: 5
  lr: 0.01
  lr_scheduler:
    step_size: 3
    gamma: 0.1
wandb:
  wandb_log: False
  project_name: 'Mandible-tracking' # 'Test-project'  'Mandible-tracking'