data:
  dataset_root: /data/Boudreault/mandible_data
  trajectories_train:
    - traj_contour0.csv
  trajectories_valid:
    - traj_contour1.csv
  trajectories_test:
    - traj_random0.csv
  rescale_pos: True
training:
  sub_model: 'resnet18' # 'resnet18' 'efficientnet-b0'
  weights_file_addon: ""  # Weights saved in f"{subnet_name}_{cam_str}cams_{nb_hidden}_{weights_file_addon}"
  use_pretrained: True
  cam_inputs:
    - Left
    - Right
    - Side
  num_fc_hidden_units: 256
  train_bs: 2
  valid_bs: 2
  test_bs: 2
  max_epochs: 5
  patience: 2
  lr: 0.005
  lr_scheduler:
    step_size: 3
    gamma: 0.1
wandb:
  wandb_log: False
  project_name: 'Test-project' # 'Test-project'  'Mandible-tracking'